version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: goraebab-frontend
    ports:
      - '3000:3000'
    environment:
      API_URL: http://host.docker.internal:2387
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: npm run dev
